server:
  port: 8080

spring:
  application.name: Expenses TG-bot
  docker:
    compose:
      enabled: true
      file: docker-compose.yml
      lifecycle-management: start_only
  datasource:
    url: jdbc:postgresql://localhost:5542/tg_budget
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:migrations
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
telegram:
  enabled: true
  bot:
    username: expenses_llocal_bot
    token: 8976027996:AAFbnkXPTUrTf5DkAnq843MH3YSiRw0a4QQ

system:
  dispatcher-capacity: 100
  chat-blocking-duration: 1000

expense:
  ml:
    enabled: true
    mock-enabled: false
    host: localhost
    port: 50051
    deadline-ms: 1500
