package com.cpallas.expenses.enums;

public enum Step {

    START_QUICK_EXPENSE,

    START_ADD_EXPENSE,
    START_DOWNLOAD_EXCEL,
    SHOW_CURRENT_STATUS,
    START_SET_MONTH_START_DAY,
    START_ADD_CATEGORY,
    START_SET_MONTH_LIMIT,

    AWAITING_MONTH_START_DAY,
    AWAITING_EXCEL_MONTH,
    AWAITING_EXPENSE_AMOUNT,
    AWAITING_EXPENSE_CATEGORY,
    AWAITING_QUICK_EXPENSE_CATEGORY,

    AWAITING_CATEGORY_NAME,
    AWAITING_EXPENSE_DESCRIPTION,
    AWAITING_QUICK_EXPENSE_CATEGORY_NAME,
    AWAITING_MONTH_LIMIT,

    SHOW_GENERAL_MENU,
    DONE
}
