package com.cpallas.expenses.enums;

public enum Step {

    AWAITING_QUICK_EXPENSE_CATEGORY,

    AWAITING_QUICK_EXPENSE_CATEGORY_NAME,
    AWAITING_EXPENSE_EDIT_ACTION,
    AWAITING_EXPENSE_EDIT_AMOUNT,
    AWAITING_EXPENSE_EDIT_DESCRIPTION,
    AWAITING_EXPENSE_EDIT_CATEGORY,
    AWAITING_EXPENSE_EDIT_CATEGORY_NAME,

    DONE
}
