package com.cpallas.expenses;

public enum Step {

    QUICK_SAVE_EXPENSE,

    SAVING_EXPENSE,
    DOWNLOAD_EXCEL_FILE,
    GETTING_CURRENT_STATUS,
    INPUT_START_DAY,
    CREATING_EXPENSE_CATEGORY,
    ADDING_MONTH_LIMITATION,

    WAITING_FOR_INPUT_START_DAY,
    WAITING_FOR_DATE_PERIOD,
    WAITING_FOR_EXPENSE_AMOUNT,
    WAITING_FOR_EXPENSE_CATEGORY,

    WAITING_FOR_EXPENSE_CATEGORY_NAME,
    WAITING_FOR_EXPENSE_DESCRIPTION,
    WAITING_FOR_MONTH_LIMITATION,

    GENERAL_MENU,
    DONE
}
